### ISSUE TITLE
Error name does not survive minification

### ISSUE THREAD

**Issue by ahutchings** [spudly/error-subclass#17]
I believe this is because the function name is mangled and so `this.constructor.name` will reference the mangled value.

There's a thread on coffeescript [here](https://github.com/jashkenas/coffeescript/issues/2052) that discusses a similar issue.

**Comment by spudly** [comment]
Fixed in v2.2.0

Add a static `displayName` property to the subclass. Since it's a string, it survives the name mangling that results from minification.
